

const AirportCode = () =>{

    const dict5 = {
        'EZE': 'Ministro Pistarini International Airport',
        'SCL': 'Arturo Merino Benítez International Airport',
        'PTY': 'Tocumen International Airport',
        'UIO': 'Mariscal Sucre International Airport',
        'SJO': 'Juan Santamaría International Airport',
        'CUN': 'Cancún International Airport',
        'HAV': 'José Martí International Airport',
        'DTW': 'Detroit Metropolitan Airport',
        'BOS': 'Logan International Airport',
        'PHL': 'Philadelphia International Airport',
        'BWI': 'Baltimore/Washington International Thurgood Marshall Airport',
        'SLC': 'Salt Lake City International Airport',
        'SAN': 'San Diego International Airport',
        'TPA': 'Tampa International Airport',
        'PDX': 'Portland International Airport',
        'STL': 'St. Louis Lambert International Airport',
        'DAL': 'Dallas Love Field',
        'AUS': 'Austin-Bergstrom International Airport',
        'RDU': 'Raleigh-Durham International Airport',
        'MCI': 'Kansas City International Airport',
        'SMF': 'Sacramento International Airport',
        'MSY': 'Louis Armstrong New Orleans International Airport',
        'CLE': 'Cleveland Hopkins International Airport',
        'SNA': 'John Wayne Airport',
        'SAT': 'San Antonio International Airport',
        'PIT': 'Pittsburgh International Airport',
        'IND': 'Indianapolis International Airport',
        'CVG': 'Cincinnati/Northern Kentucky International Airport',
        'MKE': 'Milwaukee Mitchell International Airport',
        'OMA': 'Eppley Airfield',
        'RIC': 'Richmond International Airport',
        'CHS': 'Charleston International Airport',
        'ORF': 'Norfolk International Airport',
        'TUS': 'Tucson International Airport',
        'BOI': 'Boise Airport',
        'ANC': 'Ted Stevens Anchorage International Airport',
        'SJU': 'Luis Muñoz Marín International Airport',
        'STT': 'Cyril E. King Airport',
        'STX': 'Henry E. Rohlsen Airport',
        'HNL': 'Daniel K. Inouye International Airport',
        'OGG': 'Kahului Airport',
        'KOA': 'Ellison Onizuka Kona International Airport',
        'LIH': 'Lihue Airport',
        'ITO': 'Hilo International Airport',
        'LGW': 'London Gatwick Airport',
        'LCY': 'London City Airport',
        'LTN': 'London Luton Airport',
        'STN': 'London Stansted Airport',
        'MAN': 'Manchester Airport',
        'BHX': 'Birmingham Airport',
        'GLA': 'Glasgow Airport',
        'EDI': 'Edinburgh Airport',
        'BFS': 'Belfast International Airport',
        'SNN': 'Shannon Airport',
        'ORK': 'Cork Airport',
        'ORY': 'Orly Airport',
        'BVA': 'Beauvais-Tillé Airport',
        'MRS': 'Marseille Provence Airport',
        'NCE': 'Nice Côte d\'Azur Airport',
        'LYS': 'Lyon–Saint-Exupéry Airport',
        'TLS': 'Toulouse-Blagnac Airport',
        'BOD': 'Bordeaux-Merignac Airport',
        'NAP': 'Naples International Airport',
        'CIA': 'Ciampino–G. B. Pastine International Airport',
        'MXP': 'Milan Malpensa Airport',
        'LIN': 'Milan Linate Airport',
        'BGY': 'Orio al Serio International Airport',
        'VCE': 'Venice Marco Polo Airport',
        'BLQ': 'Bologna Guglielmo Marconi Airport',
        'BER': 'Berlin Brandenburg Airport',
        'HAM': 'Hamburg Airport',
        'DUS': 'Düsseldorf Airport',
        'TXL': 'Berlin Tegel Airport',
        'SXF': 'Berlin Schönefeld Airport',
        'GVA': 'Geneva Airport',
        'BSL': 'EuroAirport Basel-Mulhouse-Freiburg',
        'BRN': 'Bern Airport',
        'LUX': 'Luxembourg Airport',
        'EIN': 'Eindhoven Airport',
        'RTM': 'Rotterdam The Hague Airport',
        'BGO': 'Bergen Airport',
        'SVG': 'Stavanger Airport',
        'VKO': 'Vnukovo International Airport',
        'KBP': 'Boryspil International Airport',
        'IEV': 'Kyiv International Airport (Zhuliany)',
        'KRK': 'John Paul II International Airport Kraków–Balice',
        'GDN': 'Gdańsk Lech Wałęsa Airport',
        'HER': 'Heraklion International Airport',
        'NBO': 'Jomo Kenyatta International Airport',
        'CPT': 'Cape Town International Airport',
        'DAR': 'Julius Nyerere International Airport',
        'ADD': 'Addis Ababa Bole International Airport',
        'LOS': 'Murtala Muhammed International Airport',
        'CAI': 'Cairo International Airport',
        'CMN': 'Mohammed V International Airport',
        'RAK': 'Marrakesh Menara Airport',
        'ALG': 'Houari Boumediene Airport',
        'TUN': 'Tunis–Carthage International Airport',
        "ATL": "Hartsfield–Jackson Atlanta International Airport",
        "PEK": "Beijing Capital International Airport",
        "LAX": "Los Angeles International Airport",
        "DXB": "Dubai International Airport",
        "HND": "Tokyo Haneda Airport",
        "ORD": "O'Hare International Airport",
        "LHR": "London Heathrow Airport",
        "HKG": "Hong Kong International Airport",
        "PVG": "Shanghai Pudong International Airport",
        "CDG": "Charles de Gaulle Airport",
        "DFW": "Dallas/Fort Worth International Airport",
        "AMS": "Amsterdam Airport Schiphol",
        "FRA": "Frankfurt Airport",
        "IST": "Istanbul Airport",
        "SIN": "Singapore Changi Airport",
        "ICN": "Incheon International Airport",
        "DEN": "Denver International Airport",
        "JFK": "John F. Kennedy International Airport",
        "BKK": "Suvarnabhumi Airport",
        "SFO": "San Francisco International Airport",
        "KUL": "Kuala Lumpur International Airport",
        "MAD": "Adolfo Suárez Madrid–Barajas Airport",
        "CAN": "Guangzhou Baiyun International Airport",
        "LAS": "McCarran International Airport",
        "MIA": "Miami International Airport",
        "MUC": "Munich Airport",
        "SEA": "Seattle-Tacoma International Airport",
        "BOM": "Chhatrapati Shivaji Maharaj International Airport",
        "EWR": "Newark Liberty International Airport",
        "GRU": "São Paulo/Guarulhos–Governador André Franco Montoro International Airport",
        "MCO": "Orlando International Airport",
        "SZX": "Shenzhen Bao'an International Airport",
        "CLT": "Charlotte Douglas International Airport",
        "IAH": "George Bush Intercontinental Airport",
        "KIX": "Kansai International Airport",
        "PHX": "Phoenix Sky Harbor International Airport",
        "SYD": "Sydney Kingsford-Smith Airport",
        "MEL": "Melbourne Airport",
        "DME": "Domodedovo International Airport",
        "FCO": "Leonardo da Vinci–Fiumicino Airport",
        "YYZ": "Toronto Pearson International Airport",
        "NRT": "Narita International Airport",
        "MSP": "Minneapolis–Saint Paul International Airport",
        "BNE": "Brisbane Airport",
        "SVO": "Sheremetyevo International Airport",
        "GIG": "Rio de Janeiro/Galeão International Airport",
        "LIM": "Jorge Chávez International Airport",
        "BOG": "El Dorado International Airport",
        "MNL": "Ninoy Aquino International Airport",
        "DEL": "Indira Gandhi International Airport",
        "JNB": "O. R. Tambo International Airport",
        "MEX": "Mexico City International Airport",
        "BCN": "Barcelona–El Prat Airport",
        "ZRH": "Zurich Airport",
        "FLL": "Fort Lauderdale–Hollywood International Airport",
        "VIE": "Vienna International Airport",
        "OSL": "Oslo Airport",
        "HEL": "Helsinki-Vantaa Airport",
        "ARN": "Stockholm Arlanda Airport",
        "CPH": "Copenhagen Airport",
        "DUB": "Dublin Airport",
        "BUD": "Budapest Ferenc Liszt International Airport",
        "WAW": "Warsaw Chopin Airport",
        "PRG": "Václav Havel Airport Prague",
        "ATH": "Athens International Airport",
        "BRU": "Brussels Airport",
        "ZAG": "Zagreb Airport",
        "LIS": "Humberto Delgado Airport",
        "LED": "Pulkovo Airport",
        "RIX": "Riga International Airport",
        "SOF": "Sofia Airport",
        "OTP": "Henri Coandă International Airport",
        "TIA": "Tirana International Airport Nënë Tereza",
        "MLA": "Malta International Airport",
        "TLL": "Tallinn Airport",
        "VNO": "Vilnius Airport",
        "SKG": "Thessaloniki Airport",
        "BEG": "Belgrade Nikola Tesla Airport",
        "SJJ": "Sarajevo International Airport",
        "PRN": "Pristina International Airport",
        "TGD": "Podgorica Airport",
        "SPU": "Split Airport",
        "DBV": "Dubrovnik Airport",
        "PUY": "Pula Airport",
        "RJK": "Rijeka Airport",
        "ZAD": "Zadar Airport",
        "OSD": "Åre Östersund Airport",
        "UME": "Umeå Airport",
        "MMX": "Malmö Airport",
        "GOT": "Göteborg Landvetter Airport",
        "NRK": "Norrköping Airport",
        "VXO": "Växjö Småland Airport",
        "KRN": "Kiruna Airport",
        "LPI": "Linköping City Airport",
        "ORB": "Örebro Airport",
        "KSD": "Karlstad Airport",
        "OSK": "Oskarshamn Airport",
        "HFS": "Hagfors Airport",
        "HLF": "Hultsfred Airport",
        "VBY": "Visby Airport",
        "BMA": "Stockholm Bromma Airport",
        "NYO": "Stockholm Skavsta Airport",
        "VST": "Stockholm Västerås Airport",
        "GSE": "Göteborg City Airport",
        "KLR": "Kalmar Airport",
        "AGH": "Ängelholm-Helsingborg Airport",
        "HAD": "Halmstad Airport",
        "JKG": "Jönköping Airport",
        "KVB": "Skövde Airport",
        "THN": "Trollhättan-Vänersborg Airport",
        "SQO": "Storuman Airport",
        "LYC": "Lycksele Airport",
        "VHM": "Vilhelmina Airport",
        "GEV": "Gällivare Airport",
        "SDL": "Sundsvall-Timrå Airport",
        "OER": "Örnsköldsvik Airport",
        "KRF": "Kramfors-Sollefteå Airport",
        "SFT": "Skellefteå Airport",
        "HUV": "Hudiksvall Airport",
        "TYF": "Torsby Airport",
        "XYC": "Söderhamn Airport",
        "MXX": "Mora-Siljan Airport",
        "IDB": "Idre Airport",
        "EVG": "Sveg Airport",
        "VVK": "Västervik Airport",
        "SPN": "Saipan International Airport",
        "MAJ": "Marshall Islands International Airport",
        "KWA": "Kwajalein Atoll",
        "ROR": "Roman Tmetuchl International Airport",
        "PNI": "Pohnpei International Airport",
        "KSA": "Kosrae International Airport",
        "YAP": "Yap International Airport",
        "TKK": "Chuuk International Airport",
        "KNH": "Kinmen Airport",
        "MZG": "Makung Airport",
        "TSA": "Taipei Songshan Airport",
        "TPE": "Taiwan Taoyuan International Airport",
        "CYI": "Chiayi Airport",
        "HUN": "Hualien Airport",
        "KHH": "Kaohsiung International Airport",
        "TXG": "Taichung International Airport",
        "TNN": "Tainan Airport",
        "TTT": "Taitung Airport",
        "WOT": "Wang-an Airport",
        "NGO": "Chubu Centrair International Airport",
        "ITM": "Osaka International Airport",
        "FUK": "Fukuoka Airport",
        "OKA": "Naha Airport",
        "CTS": "New Chitose Airport",
        "KMQ": "Komatsu Airport",
        "NGS": "Nagasaki Airport",
        "KOJ": "Kagoshima Airport",
        "KMJ": "Kumamoto Airport",
        "SDJ": "Sendai Airport",
        "TAK": "Takamatsu Airport",
        "HIJ": "Hiroshima Airport",
        "NKM": "Nagoya Airfield",
        "OKJ": "Okayama Airport",
        "ASJ": "Amami Airport",
        "AOC": "Altenburg Nobitz Airport",
        "AGB": "Augsburg Airport",
        "BRE": "Bremen Airport",
        "CGN": "Cologne Bonn Airport",
        "DTM": "Dortmund Airport",
        "ERF": "Erfurt-Weimar Airport",
        "FMO": "Münster Osnabrück International Airport",
        "HAJ": "Hannover Airport",
        "LEJ": "Leipzig/Halle Airport",
        "NUE": "Nuremberg Airport",
        "SCN": "Saarbrücken Airport",
        "STR": "Stuttgart Airport",
        "NRN": "Weeze Airport",
        "PAD": "Paderborn Lippstadt Airport",
        "RLG": "Rostock-Laage Airport",
        "DRS": "Dresden Airport",
        "FKB": "Karlsruhe/Baden-Baden Airport",
        "HHN": "Frankfurt-Hahn Airport",
        "KSF": "Kassel Airport",
        "ZQW": "Zweibrücken Airport",
        "QEF": "Egelsbach Airport",
        "LBC": "Lübeck Airport",
        "BDS": "Brindisi Airport",
        "CAG": "Cagliari Elmas Airport",
        "CTA": "Catania Fontanarossa Airport",
        "FLR": "Florence Airport",
        "GOA": "Genoa Cristoforo Colombo Airport",
        "SUF": "Lamezia Terme International Airport",
        "PMO": "Palermo Airport",
        "PSA": "Pisa International Airport",
        "TPS": "Trapani–Birgi Airport",
        "TRN": "Turin Airport",
        "VRN": "Verona Villafranca Airport",
        "TSF": "Treviso Airport",
        "AOI": "Ancona Airport",
        "BRI": "Bari Airport",
        "CFS": "Coffs Harbour Airport",
        "OOL": "Gold Coast Airport",
        "AVV": "Avalon Airport",
        "PER": "Perth Airport",
        "ADL": "Adelaide Airport",
        "HBA": "Hobart International Airport",
        "CBR": "Canberra Airport",
        "DRW": "Darwin International Airport",
        "CNS": "Cairns Airport",
        "TSV": "Townsville Airport",
        "NTL": "Newcastle Airport",
        "WGA": "Wagga Wagga Airport",
        "LST": "Launceston Airport",
        "MQL": "Mildura Airport",
        "ASP": "Alice Springs Airport",
        "AYQ": "Ayers Rock Airport",
        "HIS": "Hayman Island Airport",
        "PPP": "Whitsunday Coast Airport",
        "MCY": "Sunshine Coast Airport",
        "HTI": "Hamilton Island Airport",
        "KGC": "Kingscote Airport",
        "KNS": "King Island Airport",
        "ABX": "Albury Airport",
        "ARM": "Armidale Airport",
        "BHQ": "Broken Hill Airport",
        "BME": "Broome International Airport",
        "CDU": "Camden Airport",
        "CMA": "Cunnamulla Airport",
        "CPD": "Coober Pedy Airport",
        "DPO": "Devonport Airport",
        "ELC": "Elcho Island Airport",
        "EPR": "Esperance Airport",
        "GTE": "Groote Eylandt Airport",
        "HVB": "Hervey Bay Airport",
        "ISA": "Mount Isa Airport",
        "KTA": "Karratha Airport",
        "KNX": "Kununurra Airport",
        "LEA": "Learmonth Airport",
        "NRA": "Narrandera Airport",
        "PHE": "Port Hedland International Airport",
        "RCM": "Richmond Airport",
        "SGO": "St George Airport",
        "TWB": "Toowoomba City Aerodrome",
        "WNR": "Windorah Airport",
        "WYA": "Whyalla Airport",
        "XCH": "Christmas Island Airport",
        "ZNE": "Newman Airport"
    };

    const Airport = {};
    for (const key in dict5) {
        Airport[key] = dict5[key];
    }


    return Airport;

}

export default AirportCode;
