const  Dictionnaireville = () => {
    const dict = {
        "London": "LON",
        "Londre" : "LON",
        "New York": "NYC",
        "Los Angeles": "LAX",
        "Paris": "PAR",
        "Tokyo": "TYO",
        "Chicago": "CHI",
        "Toronto": "YTO",
        "Atlanta": "ATL",
        "Sydney": "SYD",
        "Madrid": "MAD",
        "Beijing": "BJS",
        "Seoul": "SEL",
        "Shanghai": "SHA",
        "Moscow": "MOW",
        "Dubai": "DXB",
        "Istanbul": "IST",
        "Rio de Janeiro": "RIO",
        "Berlin": "BER",
        "Mexico City": "MEX",
        "Rome": "ROM",
        "Hong Kong": "HKG",
        "Bangkok": "BKK",
        "Miami": "MIA",
        "Singapore": "SIN",
        "San Francisco": "SFO",
        "Mumbai": "BOM",
        "Amsterdam": "AMS",
        "Boston": "BOS",
        "Dallas": "DFW",
        "Vancouver": "YVR",
        "Las Vegas": "LAS",
        "Washington D.C.": "WAS",
        "Houston": "HOU",
        "Seattle": "SEA",
        "Denver": "DEN",
        "Barcelona": "BCN",
        "Milan": "MIL",
        "Vienna": "VIE",
        "Warsaw": "WAW",
        "Zurich": "ZRH",
        "Brussels": "BRU",
        "Osaka": "OSA",
        "Athens": "ATH",
        "Prague": "PRG",
        "Lisbon": "LIS",
        "Stockholm": "STO",
        "Copenhagen": "CPH",
        "Montreal": "YMQ",
        "Oslo": "OSL",
        "Helsinki": "HEL",
        "Johannesburg": "JNB",
        "Budapest": "BUD",
        "Kuala Lumpur": "KUL",
        "Munich": "MUC",
        "Frankfurt": "FRA",
        "Melbourne": "MEL",
        "Manchester": "MAN",
        "Jakarta": "JKT",
        "Auckland": "AKL",
        "Lima": "LIM",
        "Santiago": "SCL",
        "Cairo": "CAI",
        "Tel Aviv": "TLV",
        "Delhi": "DEL",
        "Minsk": "MSQ",
        "Tehran": "THR",
        "Baghdad": "BGW",
        "Riyadh": "RUH",
        "Amman": "AMM",
        "Nairobi": "NBO",
        "Dakar": "DKR",
        "Cape Town": "CPT",
        "Lagos": "LOS",
        "Accra": "ACC",
        "Kinshasa": "FIH",
        "Algiers": "ALG",
        "Tunis": "TUN",
        "Casablanca": "CAS",
        "Khartoum": "KRT",
        "Addis Ababa": "ADD",
        "Kampala": "EBB",
        "Dar es Salaam": "DAR",
        "Lusaka": "LUN",
        "Harare": "HRE",
        "Port Elizabeth": "PLZ",
        "Bloemfontein": "BFN",
        "Pretoria": "PRY",
        "Niamey": "NIM",
        "Ouagadougou": "OUA",
        "Bissau": "OXB",
        "Praia": "RAI",
        "Tirana": "TIA",
        "Luanda": "LAD",
        "Buenos Aires": "EZE",
        "Adelaide": "ADL",
        "Brisbane": "BNE",
        "Cairns": "CNS",
        "Darwin": "DRW",
        "Graz": "GRZ",
        "Innsbruck": "INN",
        "Linz": "LNZ",
        "Salzburg": "SZG",
        "Baku": "GYD",
        "Bahrain": "BAH",
        "Chittagong": "CGP",
        "Dhaka": "DAC",
        "Antwerp": "ANR",
        "Liege": "LGG",
        "La Paz": "LPB",
        "Sarajevo": "SJJ",
        "Gaborone": "GBE",
        "Calgary": "YYC",
        "Edmonton": "YEG",
        "Halifax": "YHZ",
        "Ottawa": "YOW",
        "Guangzhou": "CAN",
        "Zhengzhou": "CGO",
        "Chongqing": "CKG",
        "Changsha": "CSX",
        "Chengdu": "CTU",
        "Dalian": "DLC",
        "Fuzhou": "FOC",
        "Hefei": "HFE",
        "Hangzhou": "HGH",
        "Harbin": "HRB",
        "Jinan": "TNA",
        "Kunming": "KMG",
        "Ningbo": "NGB",
        "Nanjing": "NKG",
        "Nantong": "NTG",
        "Qingdao": "TAO",
        "Shenyang": "SHE",
        "Shenzhen": "SZX",
        "Tianjin": "TSN",
        "Weihai": "WEH",
        "Wenzhou": "WNZ",
        "Wuhan": "WUH",
        "Wuxi": "WUX",
        "Xiamen": "XMN",
        "Xi'an": "XIY",
        "Yantai": "YNT",
        "Abidjan": "ABJ",
        "Alexandria": "ALY",
        "Bordeaux": "BOD",
        "Lille": "LIL",
        "Lyon": "LYS",
        "Mulhouse": "MLH",
        "Marseille": "MRS",
        "Nice": "NCE",
        "Charles de Gaulle": "CDG",
        "Orly": "ORY",
        "Toulouse": "TLS",
        "Bremen": "BRE",
        "Cologne": "CGN",
        "Dusseldorf": "DUS",
        "Hamburg": "HAM",
        "Hanover": "HAJ",
        "Nuremberg": "NUE",
        "Stuttgart": "STR",
        "Thessaloniki": "SKG",
        "Ahmedabad": "AMD",
        "Bangalore": "BLR",
        "Kolkata": "CCU",
        "Cochin": "COK",
        "Goa": "GOI",
        "Hyderabad": "HYD",
        "Chennai": "MAA",
        "Denpasar": "DPS",
        "Surabaya": "SUB",
        "Bologna": "BLQ",
        "Florence": "FLR",
        "Genova": "GOA",
        "Malpensa": "MXP",
        "Linate": "LIN",
        "Naples": "NAP",
        "Fiumicino": "FCO",
        "Turin": "TRN",
        "Venice": "VCE",
        "Verona": "VRN",
        "Fukuoka": "FUK",
        "Hiroshima": "HIJ",
        "Kitakyushu": "KKJ",
        "Matsuyama": "MYJ",
        "Chubu Centrair": "NGO",
        "Okayama": "OKJ",
        "Okinawa": "OKA",
        "Kansai": "KIX",
        "Chitose": "CTS",
        "Sendai": "SDJ",
        "Takamatsu": "TAK",
        "Narita": "NRT",
        "Haneda": "HND",
        "Christchurch": "CHC",
        "Wellington": "WLG",
        "Austin": "AUS",
        "Washington-Baltimore": "BWI",
        "Charlotte": "CLT",
        "Cincinnati": "CVG",
        "Cleveland": "CLE",
        "Dallas-Fort Worth": "DFW",
        "Detroit": "DTW",
        "Honolulu": "HNL",
        "Houston-George Bush": "IAH",
        "Indianapolis": "IND",
        "Jacksonville": "JAX",
        "Laredo": "LRD",
        "Louisville": "SDF",
        "Minneapolis": "MSP",
        "Nashville": "BNA",
        "New Orleans": "MSY",
        "JFK": "JFK",
        "Newark": "EWR",
        "Norfolk": "ORF",
        "Philadelphia": "PHL",
        "Phoenix": "PHX",
        "Pittsburgh": "PIT",
        "Portland": "PDX",
        "San Diego": "SAN",
        "San Jose": "SJC",
        "St. Louis": "STL",
        "Washington-Dulles": "IAD",
        "Abu Dhabi": "AUH",
        "Dubai-Al Maktoum": "DWC",
        "Sharjah": "SHJ",
        "Belfast": "BFS",
        "Birmingham": "BHX",
        "Glasgow": "GLA",
        "Leeds": "LBA",
        "Heathrow": "LHR",
        "Liverpool": "LPL",
        "Newcastle": "NCL",
        "Southampton": "SOU",
        "Libreville": "LBV",
        "Durban": "DUR",
        "Mombasa": "MBA",
        "Kisumu": "KIS",
        "Eldoret": "EDL",
        "Malindi": "MYD",
        "Luxor": "LXR",
        "Sharm El Sheikh": "SSH",
        "Hurghada": "HRG",
        "Abuja": "ABV",
        "Kano": "KAN",
        "Port Harcourt": "PHC",
        "Ibadan": "IBA",
        "Kaduna": "KAD",
        "Marrakech": "RAK",
        "Agadir": "AGA",
        "Tangier": "TNG",
        "Fez": "FEZ",
        "Rabat": "RBA",
        "Kumasi": "KMS",
        "Tamale": "TML",
        "Takoradi": "TKD",
        "Sunyani": "NYI",
        "Cape Coast": "CCO",
        "Dire Dawa": "DIR",
        "Bahir Dar": "BJR",
        "Gondar": "GDQ",
        "Mekele": "MQX",
        "Asmara": "ASM",
        "Kigali": "KGL",
        "Bujumbura": "BJM",
        "N'Djamena": "NDJ",
        "Djibouti City": "JIB",
        "Mogadishu": "MGQ",
        "Mauritius": "MRU",
        "Saint-Denis": "RUN",
        "Maputo": "MPM",
        "Beira": "BEW",
        "Nampula": "APL",
        "Pemba": "POL",
        "Quelimane": "UEL",
        "Lichinga": "VXC",
        "Huambo": "NOV",
        "Lobito": "SDD",
        "Benguela": "BUG",
        "Namibe": "MSZ",
        "Windhoek": "WDH",
        "Walvis Bay": "WVB",
        "Swakopmund": "SWP",
        "Tsumeb": "TSB",
        "Francistown": "FRW",
        "Ndola": "NLA",
        "Livingstone": "LVI",
        "Kitwe": "KIW",
        "Bulawayo": "BUQ",
        "Chitungwiza": "CHJ",
        "Mutare": "UTA",
        "Masvingo": "MVZ",
        "Kwekwe": "KWE",
        "Blantyre": "BLZ",
        "Lilongwe": "LLW",
        "Mzuzu": "ZZU",
        "Zomba": "ZOM",
        "Maseru": "MSU",
        "Nouakchott": "NKC",
        "Bamako": "BKO",
        "Thiès": "TEY",
        "Guédiawaye": "GUE",
        "Saint-Louis": "XLS",
        "Touba": "TOB",
        "Pikine": "PIK",
        "Diamniadio": "DIA",
        "Conakry": "CKY",
        "Nzérékoré": "NZE",
        "Kindia": "GII",
        "Freetown": "FNA",
        "Bo": "KBS",
        "Kenema": "KEN",
        "Koidu": "KDU",
        "Butare": "BTQ",
        "Gitarama": "GYI",
        "Ruhengeri": "RHG",
        "Gisenyi": "GYI",
        "Juba": "JUB",
        "Wau": "WUU",
        "Malakal": "MAK",
        "Bahar Dar": "BJR",
        "Massawa": "MSW",

    };
    const lowerCaseDict = {};
    for (const key in dict) {
        lowerCaseDict[key.toLowerCase()] = dict[key];
    }


    return lowerCaseDict;
}

export default Dictionnaireville;