

const CompagnieCarrier = () =>{
    const dict3 = {
        'AA': 'American Airlines',
        'AF': 'Air France',
        'AI': 'Air India',
        'BA': 'British Airways',
        'CA': 'Air China',
        'CX': 'Cathay Pacific',
        'DL': 'Delta Air Lines',
        'EK': 'Emirates',
        'EY': 'Etihad Airways',
        'GA': 'Garuda Indonesia',
        'JL': 'Japan Airlines',
        'KL': 'KLM Royal Dutch Airlines',
        'LH': 'Lufthansa',
        'LX': 'Swiss International Air Lines',
        'MH': 'Malaysia Airlines',
        'NZ': 'Air New Zealand',
        'QF': 'Qantas',
        'QR': 'Qatar Airways',
        'SA': 'South African Airways',
        'SQ': 'Singapore Airlines',
        'SU': 'Aeroflot',
        'TK': 'Turkish Airlines',
        'UA': 'United Airlines',
        'VA': 'Virgin Australia',
        'VN': 'Vietnam Airlines',
        'VS': 'Virgin Atlantic',
        'WS': 'WestJet',
        'WN': 'Southwest Airlines',
        'AC': 'Air Canada',
        'AZ': 'Alitalia',
        'SK': 'Scandinavian Airlines',
        'IB': 'Iberia',
        'TP': 'TAP Portugal',
        'OS': 'Austrian Airlines',
        'AY': 'Finnair',
        'SN': 'Brussels Airlines',
        'LO': 'LOT Polish Airlines',
        'OK': 'Czech Airlines',
        'RO': 'TAROM',
        'HU': 'Hainan Airlines',
        'MU': 'China Eastern Airlines',
        'CZ': 'China Southern Airlines',
        'MF': 'XiamenAir',
        'BR': 'EVA Air',
        'CI': 'China Airlines',
        'TG': 'Thai Airways',
        'PG': 'Bangkok Airways',
        'UL': 'SriLankan Airlines',
        'G8': 'GoAir',
        '6E': 'IndiGo',
        'UK': 'Vistara',
        'I5': 'AirAsia India',
        'SG': 'SpiceJet',
        '9W': 'Jet Airways',
        'FZ': 'Flydubai',
        'G9': 'Air Arabia',
        'RJ': 'Royal Jordanian',
        'MS': 'EgyptAir',
        'ET': 'Ethiopian Airlines',
        'KQ': 'Kenya Airways',
        'AT': 'Royal Air Maroc',
        'TN': 'Air Tahiti Nui',
        'FJ': 'Fiji Airways',
        'HA': 'Hawaiian Airlines',
        'NH': 'All Nippon Airways',
        'KE': 'Korean Air',
        'OZ': 'Asiana Airlines',
        'PR': 'Philippine Airlines',
        'Z2': 'Philippines AirAsia',
        'TR': 'Scoot',
        'MI': 'SilkAir',
        'TZ': 'Scoot',
        'FD': 'Thai AirAsia',
        'SL': 'Thai Lion Air',
        'VJ': 'VietJet Air',
        'SV': 'Saudia',
        'KU': 'Kuwait Airways',
        'WY': 'Oman Air',
        'GF': 'Gulf Air',
        'ME': 'Middle East Airlines',
        'AS': 'Alaska Airlines',
        'BI': 'Royal Brunei Airlines',
        'B6': 'JetBlue',
        'F9': 'Frontier Airlines',
        'NK': 'Spirit Airlines',
        'SY': 'Sun Country Airlines',
        '4O': 'Interjet',
        'AM': 'Aeromexico',
        'AR': 'Aerolineas Argentinas',
        'AV': 'Avianca',
        'CM': 'Copa Airlines',
        'LA': 'LATAM Airlines',
        'LP': 'LATAM Peru',
        'JJ': 'LATAM Brazil',
        'G3': 'GOL Linhas Aereas',
        'AD': 'Azul Brazilian Airlines',
        'F4': 'Fischer Air',
        'U2': 'easyJet',
        'FR': 'Ryanair',
        'EZY': 'easyJet UK',
        'VY': 'Vueling',
        'W6': 'Wizz Air',
        'A3': 'Aegean Airlines',
        'BT': 'Air Baltic',
        'LY': 'El Al Israel Airlines',
        'HY': 'Uzbekistan Airways',
        'KC': 'Air Astana',
        'HM': 'Air Seychelles',
        'MK': 'Air Mauritius',
        'TU': 'Tunisair',
        'JM': 'Air Jamaica',
        'TA': 'TACA Airlines',
        'WB': 'RwandAir',
        'PW': 'Precision Air',
        '8Z': 'Wizz Air Hungary',
        'KP': 'ASKY Airlines',
        'MN': 'Kulula',
        'DT': 'TAAG Angola Airlines',
        '4Z': 'Airlink',
        'JE': 'Mango',
        'BW': 'Caribbean Airlines',
        'WG': 'Sunwing Airlines',
        'C6': 'CanJet',
        'TS': 'Air Transat',
        'PD': 'Porter Airlines',
        'ZY': 'Azul Conecta',
        'PZ': 'LATAM Paraguay',
        'H2': 'Sky Airline',
        'J2': 'Azerbaijan Airlines',
        'ZP': 'Paranair',
        'W2': 'FlexFlight',
        '6X': 'TUIfly Belgium',
        '5X': 'UPS Airlines',
        'FX': 'FedEx Express',
        'RU': 'AirBridgeCargo Airlines',
        'CV': 'Cargolux',
        '5Y': 'Atlas Air',
        'N8': 'National Airlines',
        'X7': 'Air Tanzania',
        '3S': 'Air Seychelles',
        'K8': 'Airlink Zambia',
        'ZF': 'Azur Air Ukraine',
        'EO': 'Pegas Fly',
        'U6': 'Ural Airlines',
        'IK': 'Ikar Airlines',
        'IO': 'IrAero',
        'WZ': 'Red Wings Airlines',
        'UC': 'LATAM Cargo Chile',
        'MP': 'Martinair Cargo',
        '5S': 'Global Air',
        '8Y': 'China Postal Airlines',
        'M8': 'Magellan Air',
        'X2': 'AirAsia X',
        'XT': 'Indonesia AirAsia X',
        'D7': 'AirAsia X',
        'AK': 'AirAsia',
        'QZ': 'Indonesia AirAsia',
        'PQ': 'SkyUp Airlines',
        'BB': 'Seaborne Airlines',
        'IN': 'NAM Air',
        'IU': 'Super Air Jet',
        'JT': 'Lion Air',
        'OD': 'Malindo Air',
        'H9': 'Himalaya Airlines',
        'UB': 'Myanmar National Airlines',
        'K6': 'Cambodia Angkor Air',
        'QD': 'JC International Airlines',
        'KZ': 'Nippon Cargo Airlines',
        'IC': 'Indian Airlines',
        'IX': 'Air India Express',
        'DN': 'Air Deccan',
        'J9': 'Jazeera Airways',
        'Q5': '40-Mile Air',
        'QB': 'Qeshm Air',
        'QN': 'Skytrans',
        'JQ': 'Jetstar Airways',
        '3K': 'Jetstar Asia Airways',
        'GK': 'Jetstar Japan',
        'BL': 'Jetstar Pacific',
        'YB': 'Perimeter Aviation',
        'NC': 'Northern Air Cargo',
        'KS': 'PenAir',
        'OO': 'SkyWest Airlines',
        'MQ': 'Envoy Air',
        'YX': 'Republic Airways',
        'OH': 'PSA Airlines',
        'G4': 'Allegiant Air',
        'EV': 'ExpressJet',
        'YV': 'Mesa Airlines',
        'QX': 'Horizon Air',
        'ZW': 'Air Wisconsin',
        'AX': 'Trans States Airlines',
        'EM': 'Empire Airlines',
        'KH': 'Aloha Air Cargo',
        '3M': 'Silver Airways',
        'PT': 'Piedmont Airlines',
        '4B': 'Boutique Air',
        '9K': 'Cape Air',
        '5G': 'Skyservice Airlines',
        'WQ': 'Swift Air',
        'XP': 'Xtra Airways',
        'J5': 'Alaska Seaplane Service',
        '9H': 'Alliance Air',
        '5T': 'Canadian North',
        '8P': 'Pacific Coastal Airlines',
        'PB': 'PAL Airlines',
        'YN': 'Air Creebec',
        'ZX': 'Air Georgian',
        'QK': 'Jazz Aviation',
        'RV': 'Air Canada Rouge',
        'WO': 'Swoop',
        '7F': 'First Air',
        '9N': 'Tropic Air',
        'Y4': 'Volaris',
        'VB': 'Viva Aerobus',
        'QA': 'Viva Air Colombia',
        'VE': 'EasyFly',
        'FO': 'Flybondi',
        'P9': 'Peruvian Airlines',
        'W8': 'Cargojet Airways',
        'N4': 'Nordwind Airlines',
        'DP': 'Pobeda',
        'YC': 'Yamal Airlines',
        'S7': 'S7 Airlines',
        'R3': 'Yakutia Airlines',
        'FV': 'Rossiya Airlines',
        'N5': 'Nile Air',
        '8U': 'Afriqiyah Airways',
        'AH': 'Air Algerie',
        'W3': 'Arik Air',
        'FN': 'Fastjet',
        '3Q': 'China Yunnan Airlines',
        '3U': 'Sichuan Airlines',
        'ZH': 'Shenzhen Airlines',
        'JD': 'Capital Airlines',
        'GS': 'Tianjin Airlines',
        '8L': 'Lucky Air',
        'DR': 'Ruili Airlines',
        'GJ': 'Loong Air',
        'PN': 'West Air',
        'QW': 'Qingdao Airlines',
        'KN': 'China United Airlines',
        'NS': 'Hebei Airlines',
        'EU': 'Chengdu Airlines',
        'DZ': 'Donghai Airlines',
        'KY': 'Kunming Airlines',
        'GX': 'GX Airlines',
        'G5': 'China Express Airlines',
        'FU': 'Fuzhou Airlines',
        'ID': 'Batik Air',
        'QG': 'Citilink',

    };

    const compagnieVol = {};
    for (const key in dict3){
        compagnieVol[key] = dict3[key]
    }
    return  compagnieVol;
}

export default CompagnieCarrier;